import test from 'node:test';import assert from 'node:assert/strict';import {buildRequest,videoUrl,ORIGINS,runRequest,errorMessage} from '../src/api.js';
const v={model:'hq',first:new Blob(['image']),last:null,prompt:'test',negative:'avoid',duration:3.5,fps:'16',upscale:true,steps:6,guidance:1,seed:42,random:true,variant:0};
test('HQ preserves all eleven inputs and optional last frame',()=>{const r=buildRequest(v);assert.equal(r.endpoint,'/generate_video');assert.equal(Object.keys(r.payload).length,11);assert.equal(r.payload.last_image,null);assert.equal(r.payload.duration_seconds,3.5);assert.equal(r.payload.frame_multiplier,16);assert.equal(r.payload.input_image,v.first);});
test('all five previews use four inputs and their own endpoint',()=>{for(let variant=0;variant<5;variant++){const r=buildRequest({...v,variant},true);assert.equal(r.endpoint,variant?`/preview_effect_${variant}`:'/preview_effect');assert.equal(Object.keys(r.payload).length,4);}});
test('rejects invalid values before network use',()=>{for(const patch of [{first:null},{duration:NaN},{duration:21},{steps:31},{seed:-1},{fps:'999'},{prompt:''}])assert.throws(()=>buildRequest({...v,...patch}));});
test('MiniMax supports text-only and exact parameter names',()=>{const r=buildRequest({...v,model:'mini',first:null,duration:6,canvas:'960x544 · 16:9 fast',lora:'off'});assert.equal(r.endpoint,'/output_video');assert.equal(r.payload.in_1,null);assert.equal(Object.keys(r.payload).length,9);assert.throws(()=>buildRequest({...v,model:'mini',duration:3.5}));});
test('video extraction accepts nested output and rejects unsafe URLs',()=>{const url=ORIGINS.hq+'/gradio_api/file=/tmp/a.mp4';assert.equal(videoUrl([{video:{url}}],ORIGINS.hq),url);assert.equal(videoUrl([{path:'/tmp/a.mp4'}],ORIGINS.hq),url);assert.equal(videoUrl(['javascript:alert(1)'],ORIGINS.hq),null);assert.equal(videoUrl(['https://evil.test/file'],ORIGINS.hq),null);});
test('requests retain chosen endpoint, report status and close connection',async()=>{let closed=false;const got=[];const Client={connect:async(origin,opts)=>{assert.equal(origin,ORIGINS.hq);assert.equal(opts.record_history,false);return{submit:async function*(endpoint,payload){assert.equal(endpoint,'/preview_effect_4');yield{type:'status',stage:'pending'};yield{type:'data',data:['16 FPS']};},close(){closed=true;}};}};await runRequest(Client,'hq','',buildRequest({...v,variant:4},true),{data:x=>got.push(x)});assert.deepEqual(got,[['16 FPS']]);assert.ok(closed);});
test('provider errors do not become success',async()=>{const Client={connect:async()=>({submit:async function*(){yield{type:'status',stage:'error',message:'quota'};},close(){}})};await assert.rejects(runRequest(Client,'hq','',buildRequest(v)),/quota/);assert.ok(!errorMessage(Error('invalid hf_abc123')).includes('hf_abc123'));});


test('cancellation while connecting never submits a request',async()=>{let resolveConnection,closeCount=0,cancel;const Client={connect:()=>new Promise(resolve=>{resolveConnection=resolve;})};const task=runRequest(Client,'hq','',buildRequest(v),{control:fn=>cancel=fn});cancel();resolveConnection({submit(){throw Error('must not submit');},close(){closeCount++;}});await task;assert.equal(closeCount,1);});
test('empty provider response cannot report success',async()=>{const Client={connect:async()=>({submit:async function*(){yield{type:'status',stage:'complete'};},close(){}})};await assert.rejects(runRequest(Client,'hq','',buildRequest(v)),/chưa trả kết quả/);});
